version: '3.9'

services:
  db:
    image: postgres:17
    container_name: urbanfeast_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: majid
      POSTGRES_DB: urbanfeast
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: urbanfeast_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
